# Generated by Django 4.2.11 on 2024-04-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_default_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_medium_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_high_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
