version: '3'

services:
  redis:
    image: redis:alpine

  db:
    image: postgres
    environment:
      POSTGRES_USER: famProject
      POSTGRES_DB: famProjectDB
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data

  famProject:
    image: famproject:latest
    hostname: famproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/famProject
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
    command: celery -A famProject worker --loglevel=info
    volumes:
      - .:/famProject
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
    command: celery -A famProject beat --loglevel=info
    volumes:
      - .:/famProject
    depends_on:
      - redis
      - db

volumes:
  pgdata:
